### ISSUE TITLE
Contribution guidance

### ISSUE THREAD

**Issue by richleland** [angular-ui/ui-ace#86]
Hi there - my team uses angular-ui-ace and would love to help with some outstanding issues:

* Existing issues #65, #43, and #29
* Helping however possible with the release cycle time - from getting a release tagged to having it available via bower
* Triage/label/review issues/PRs

I know I can just do PRs on the first three, and we've already dealt with things like #43 via bower overrides, but what about the second? I noticed there is a bower branch, tags, a download link to the tag on http://angular-ui.github.io/ui-ace/. Just looking for some contribution guidance here. Let me know where you could use the most help.

**Comment by douglasduteil** [comment]
Hi @richleland 

Thanks for the support.

I'm actually in a "bad" situation because I'm "maintaining" this repo that I don't use anymore...
As a result, I have problem deciding whether or not a PR is relevant.
So I'm looking forward to see more live example of the use of UI.Ace.
And I'm planing to make a **UI.Ace Kitchen Sink** similar to the [Ace Kitchen Sink](http://ace.c9.io/build/kitchen-sink.html).

I have to take the time to make a actual contribution guidance explaining at least the role of the [Angular UI Publisher](https://github.com/angular-ui/angular-ui-publisher) but meanwhile I'm looking forward for your reviews.

Thanks.
Douglas.
